source 'https://github.com/CocoaPods/Specs.git'
project 'IOS-MapFeature-Form'
use_frameworks!

target 'IOS-MapFeature-Form_Example' do
  pod 'IOS-MapFeature-Form', :path => '../'
end

target 'IOS-MapFeature-Form_Tests' do
  pod 'IOS-MapFeature-Form', :path => '../'

  
end
